### ISSUE TITLE
remote couldn't create file: Read-only file system

### ISSUE THREAD

**Issue by SusenkaOREOcze** [ronald8192/AndroidWinXPBootAnimation#1]
when i use **adb push /path/bootanimation.zip /system/media/bootanimation.zip.new**
it says:

```
 1 file pushed, 0 skipped. 39.9 MB/s (1023843 bytes in 0.024s) adb: error: failed to copy
remote couldn't create file: Read-only file system
```

i dont know what to do
i tried to root my phone but i didnt find anything working can somebody help me pls

**Comment by ronald8192** [comment]
Try remounting your file system to rw first: `adb shell mount -o rw,remount /;`
